/* Blocks for the drag-and-drop editor. "el" blocks are small pieces that can
   go anywhere (inside cards, columns, sections); "section" blocks are full-width
   page sections and are dropped between other sections. Styles: /eb-blocks.css */
(function () {
  "use strict";
  var IMG = "/blog/wp-content/uploads/2025/09/online-digital-marketing-course.webp";
  var IMG2 = "/blog/wp-content/uploads/2025/09/digital-marketing-mentorship-program.webp";
  var IMG3 = "/blog/wp-content/uploads/2025/09/best-digital-marketing-course.webp";
  function section(inner, cls) { return '<section class="ebb-section' + (cls ? " " + cls : "") + '"><div class="ebb-wrap">' + inner + "</div></section>"; }
  function card(n, t, p) { return '<div class="ebb-card"><div class="ebb-icon">' + n + "</div><h3>" + t + "</h3><p>" + p + "</p></div>"; }
  function person(img, name, role, quote) { return '<div class="ebb-card"><p class="ebb-quote">“' + quote + '”</p><div class="ebb-person"><img src="' + img + '" alt="' + name + '"><div><b>' + name + "</b><span>" + role + "</span></div></div></div>"; }

  window.EB.blocks = [
    { id: "heading", group: "Basics", name: "Heading", icon: "H", kind: "el", html: '<h2 class="ebb-h">Your heading here</h2>' },
    { id: "text", group: "Basics", name: "Text", icon: "¶", kind: "el", html: '<p class="ebb-p">Write your text here. Double-click to edit it.</p>' },
    { id: "button", group: "Basics", name: "Button", icon: "▭", kind: "el", html: '<a class="ebb-btn" href="/contact">Enquire now</a>' },
    { id: "image", group: "Basics", name: "Image", icon: "▣", kind: "el", html: '<figure class="ebb-img"><img src="' + IMG + '" alt="Describe this image"></figure>' },
    { id: "video", group: "Basics", name: "YouTube video", icon: "▶", kind: "el", html: '<div class="ebb-video"><iframe src="https://www.youtube-nocookie.com/embed/" title="Video" loading="lazy" allowfullscreen></iframe></div>' },
    { id: "spacer", group: "Basics", name: "Space", icon: "↕", kind: "el", html: '<div class="ebb-space"></div>' },
    { id: "divider", group: "Basics", name: "Divider", icon: "—", kind: "el", html: '<hr class="ebb-hr">' },

    { id: "hero", group: "Sections", name: "Hero banner", icon: "★", kind: "section", html: section('<div class="ebb-center ebb-lead"><h2>Start your career in digital marketing</h2><p>Learn from industry experts with live projects, mentorship and placement support.</p><div class="ebb-btns"><a class="ebb-btn" href="/contact">Book a free session</a><a class="ebb-btn ebb-outline" href="/digital-marketing-course">View course</a></div></div>', "ebb-dark") },
    { id: "imagetext", group: "Sections", name: "Image + text", icon: "◧", kind: "section", html: section('<div class="ebb-grid ebb-g2"><figure class="ebb-img"><img src="' + IMG + '" alt="Students learning digital marketing"></figure><div><h2>Learn by doing real projects</h2><p>Every module ends with hands-on work on live campaigns, so you graduate with a portfolio employers can see.</p><div class="ebb-btns"><a class="ebb-btn" href="/contact">Talk to a counsellor</a></div></div></div>') },
    { id: "textimage", group: "Sections", name: "Text + image", icon: "◨", kind: "section", html: section('<div class="ebb-grid ebb-g2"><div><h2>Mentors who work in the industry</h2><p>Get feedback from practitioners who run campaigns for real brands every day.</p><div class="ebb-btns"><a class="ebb-btn" href="/alumni">Meet our alumni</a></div></div><figure class="ebb-img"><img src="' + IMG2 + '" alt="Mentorship session"></figure></div>', "ebb-soft") },
    { id: "features", group: "Sections", name: "3 feature cards", icon: "▦", kind: "section", html: section('<div class="ebb-center ebb-lead"><h2>Why learn with eBuddha</h2><p>Everything you need to go from beginner to job-ready.</p></div><div class="ebb-grid ebb-g3">' + card("1", "Live classes", "Interactive sessions with experts, plus recordings to revise anytime.") + card("2", "Real projects", "Work on live campaigns and build a portfolio that gets you hired.") + card("3", "Placement support", "Resume reviews, mock interviews and introductions to hiring partners.") + "</div>", "ebb-soft") },
    { id: "stats", group: "Sections", name: "Numbers", icon: "#", kind: "section", html: section('<div class="ebb-grid ebb-g4 ebb-center"><div class="ebb-stat"><b>21.5k+</b>Learners mentored</div><div class="ebb-stat"><b>500+</b>Hiring partners</div><div class="ebb-stat"><b>4.8/5</b>Average rating</div><div class="ebb-stat"><b>100%</b>Practical training</div></div>', "ebb-dark") },
    { id: "cta", group: "Sections", name: "Call to action", icon: "➜", kind: "section", html: section('<div class="ebb-center ebb-lead"><h2>Ready to get job-ready?</h2><p>Talk to a counsellor and find the right program for you.</p><div class="ebb-btns"><a class="ebb-btn" href="/contact">Request a callback</a></div></div>', "ebb-dark") },
    { id: "faq", group: "Sections", name: "FAQ", icon: "?", kind: "section", html: section('<div class="ebb-center"><h2>Frequently asked questions</h2></div><div class="ebb-faq"><details open><summary>Who is this course for?</summary><p>Students, graduates, working professionals and business owners who want practical digital skills.</p></details><details><summary>Are the classes live?</summary><p>Yes. Classes are live and interactive, and every session is recorded.</p></details><details><summary>Do you help with placements?</summary><p>Yes. You get resume reviews, mock interviews and introductions to hiring partners.</p></details></div>') },
    { id: "testimonials", group: "Sections", name: "Testimonials", icon: "❝", kind: "section", html: section('<div class="ebb-center"><h2>What our learners say</h2></div><div class="ebb-grid ebb-g3">' + person("/images/students/ikccha-gupta.png", "Ikccha", "TechXR", "The live projects gave me real confidence. I could show my work in every interview.") + person("/images/students/kartavya-krishne.png", "Kartavya", "RcadTech", "Mentors explained everything practically, and the placement team kept supporting me.") + person("/images/students/monika-thapa.png", "Monika", "Digital marketer", "I started with zero experience and now manage campaigns for real clients.") + "</div>", "ebb-soft") },
    { id: "gallery", group: "Sections", name: "Image gallery", icon: "▤", kind: "section", html: section('<h2 class="ebb-center">Life at eBuddha</h2><div class="ebb-grid ebb-g3 ebb-gallery"><img src="' + IMG + '" alt="Classroom"><img src="' + IMG2 + '" alt="Mentorship"><img src="' + IMG3 + '" alt="Workshop"></div>') },
    { id: "columns", group: "Sections", name: "Two columns", icon: "‖", kind: "section", html: section('<div class="ebb-grid ebb-g2" style="align-items:start"><div class="ebb-col"><h3>Left column</h3><p>Drag blocks in here, or double-click to edit this text.</p></div><div class="ebb-col"><h3>Right column</h3><p>Drag blocks in here, or double-click to edit this text.</p></div></div>') }
  ];
})();
